/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedWeeklyResetRouteImport } from './routes/_authenticated/weekly-reset'
import { Route as AuthenticatedTomorrowRouteImport } from './routes/_authenticated/tomorrow'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedRoutinesRouteImport } from './routes/_authenticated/routines'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedHouseholdRouteImport } from './routes/_authenticated/household'
import { Route as AuthenticatedCalendarImportRouteImport } from './routes/_authenticated/calendar-import'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedSetupSyncRouteImport } from './routes/_authenticated/setup.sync'
import { Route as AuthenticatedSetupNotificationsRouteImport } from './routes/_authenticated/setup.notifications'
import { Route as AuthenticatedSetupGmailRouteImport } from './routes/_authenticated/setup.gmail'
import { Route as AuthenticatedSetupAndroidRouteImport } from './routes/_authenticated/setup.android'
import { Route as AuthenticatedPlannerPreferencesRouteImport } from './routes/_authenticated/planner.preferences'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeeklyResetRoute =
  AuthenticatedWeeklyResetRouteImport.update({
    id: '/weekly-reset',
    path: '/weekly-reset',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTomorrowRoute = AuthenticatedTomorrowRouteImport.update({
  id: '/tomorrow',
  path: '/tomorrow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutinesRoute = AuthenticatedRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHouseholdRoute = AuthenticatedHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarImportRoute =
  AuthenticatedCalendarImportRouteImport.update({
    id: '/calendar-import',
    path: '/calendar-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSetupSyncRoute = AuthenticatedSetupSyncRouteImport.update({
  id: '/setup/sync',
  path: '/setup/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupNotificationsRoute =
  AuthenticatedSetupNotificationsRouteImport.update({
    id: '/setup/notifications',
    path: '/setup/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetupGmailRoute = AuthenticatedSetupGmailRouteImport.update({
  id: '/setup/gmail',
  path: '/setup/gmail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupAndroidRoute =
  AuthenticatedSetupAndroidRouteImport.update({
    id: '/setup/android',
    path: '/setup/android',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlannerPreferencesRoute =
  AuthenticatedPlannerPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRoute
  '/calendar-import': typeof AuthenticatedCalendarImportRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/tomorrow': typeof AuthenticatedTomorrowRoute
  '/weekly-reset': typeof AuthenticatedWeeklyResetRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/planner/preferences': typeof AuthenticatedPlannerPreferencesRoute
  '/setup/android': typeof AuthenticatedSetupAndroidRoute
  '/setup/gmail': typeof AuthenticatedSetupGmailRoute
  '/setup/notifications': typeof AuthenticatedSetupNotificationsRoute
  '/setup/sync': typeof AuthenticatedSetupSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRoute
  '/calendar-import': typeof AuthenticatedCalendarImportRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/tomorrow': typeof AuthenticatedTomorrowRoute
  '/weekly-reset': typeof AuthenticatedWeeklyResetRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/planner/preferences': typeof AuthenticatedPlannerPreferencesRoute
  '/setup/android': typeof AuthenticatedSetupAndroidRoute
  '/setup/gmail': typeof AuthenticatedSetupGmailRoute
  '/setup/notifications': typeof AuthenticatedSetupNotificationsRoute
  '/setup/sync': typeof AuthenticatedSetupSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/calendar-import': typeof AuthenticatedCalendarImportRoute
  '/_authenticated/household': typeof AuthenticatedHouseholdRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/routines': typeof AuthenticatedRoutinesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/tomorrow': typeof AuthenticatedTomorrowRoute
  '/_authenticated/weekly-reset': typeof AuthenticatedWeeklyResetRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/planner/preferences': typeof AuthenticatedPlannerPreferencesRoute
  '/_authenticated/setup/android': typeof AuthenticatedSetupAndroidRoute
  '/_authenticated/setup/gmail': typeof AuthenticatedSetupGmailRoute
  '/_authenticated/setup/notifications': typeof AuthenticatedSetupNotificationsRoute
  '/_authenticated/setup/sync': typeof AuthenticatedSetupSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/index'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/calendar-import'
    | '/household'
    | '/inbox'
    | '/planner'
    | '/privacy'
    | '/routines'
    | '/tasks'
    | '/today'
    | '/tomorrow'
    | '/weekly-reset'
    | '/welcome'
    | '/.lovable/oauth/consent'
    | '/planner/preferences'
    | '/setup/android'
    | '/setup/gmail'
    | '/setup/notifications'
    | '/setup/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/index'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/calendar-import'
    | '/household'
    | '/inbox'
    | '/planner'
    | '/privacy'
    | '/routines'
    | '/tasks'
    | '/today'
    | '/tomorrow'
    | '/weekly-reset'
    | '/welcome'
    | '/.lovable/oauth/consent'
    | '/planner/preferences'
    | '/setup/android'
    | '/setup/gmail'
    | '/setup/notifications'
    | '/setup/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/index'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/_authenticated/calendar-import'
    | '/_authenticated/household'
    | '/_authenticated/inbox'
    | '/_authenticated/planner'
    | '/_authenticated/privacy'
    | '/_authenticated/routines'
    | '/_authenticated/tasks'
    | '/_authenticated/today'
    | '/_authenticated/tomorrow'
    | '/_authenticated/weekly-reset'
    | '/_authenticated/welcome'
    | '/.lovable/oauth/consent'
    | '/_authenticated/planner/preferences'
    | '/_authenticated/setup/android'
    | '/_authenticated/setup/gmail'
    | '/_authenticated/setup/notifications'
    | '/_authenticated/setup/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weekly-reset': {
      id: '/_authenticated/weekly-reset'
      path: '/weekly-reset'
      fullPath: '/weekly-reset'
      preLoaderRoute: typeof AuthenticatedWeeklyResetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tomorrow': {
      id: '/_authenticated/tomorrow'
      path: '/tomorrow'
      fullPath: '/tomorrow'
      preLoaderRoute: typeof AuthenticatedTomorrowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routines': {
      id: '/_authenticated/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthenticatedRoutinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/household': {
      id: '/_authenticated/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthenticatedHouseholdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar-import': {
      id: '/_authenticated/calendar-import'
      path: '/calendar-import'
      fullPath: '/calendar-import'
      preLoaderRoute: typeof AuthenticatedCalendarImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup/sync': {
      id: '/_authenticated/setup/sync'
      path: '/setup/sync'
      fullPath: '/setup/sync'
      preLoaderRoute: typeof AuthenticatedSetupSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/notifications': {
      id: '/_authenticated/setup/notifications'
      path: '/setup/notifications'
      fullPath: '/setup/notifications'
      preLoaderRoute: typeof AuthenticatedSetupNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/gmail': {
      id: '/_authenticated/setup/gmail'
      path: '/setup/gmail'
      fullPath: '/setup/gmail'
      preLoaderRoute: typeof AuthenticatedSetupGmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/android': {
      id: '/_authenticated/setup/android'
      path: '/setup/android'
      fullPath: '/setup/android'
      preLoaderRoute: typeof AuthenticatedSetupAndroidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner/preferences': {
      id: '/_authenticated/planner/preferences'
      path: '/preferences'
      fullPath: '/planner/preferences'
      preLoaderRoute: typeof AuthenticatedPlannerPreferencesRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPlannerRouteChildren {
  AuthenticatedPlannerPreferencesRoute: typeof AuthenticatedPlannerPreferencesRoute
}

const AuthenticatedPlannerRouteChildren: AuthenticatedPlannerRouteChildren = {
  AuthenticatedPlannerPreferencesRoute: AuthenticatedPlannerPreferencesRoute,
}

const AuthenticatedPlannerRouteWithChildren =
  AuthenticatedPlannerRoute._addFileChildren(AuthenticatedPlannerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCalendarImportRoute: typeof AuthenticatedCalendarImportRoute
  AuthenticatedHouseholdRoute: typeof AuthenticatedHouseholdRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRouteWithChildren
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedRoutinesRoute: typeof AuthenticatedRoutinesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTomorrowRoute: typeof AuthenticatedTomorrowRoute
  AuthenticatedWeeklyResetRoute: typeof AuthenticatedWeeklyResetRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedSetupAndroidRoute: typeof AuthenticatedSetupAndroidRoute
  AuthenticatedSetupGmailRoute: typeof AuthenticatedSetupGmailRoute
  AuthenticatedSetupNotificationsRoute: typeof AuthenticatedSetupNotificationsRoute
  AuthenticatedSetupSyncRoute: typeof AuthenticatedSetupSyncRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCalendarImportRoute: AuthenticatedCalendarImportRoute,
  AuthenticatedHouseholdRoute: AuthenticatedHouseholdRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRouteWithChildren,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedRoutinesRoute: AuthenticatedRoutinesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTomorrowRoute: AuthenticatedTomorrowRoute,
  AuthenticatedWeeklyResetRoute: AuthenticatedWeeklyResetRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedSetupAndroidRoute: AuthenticatedSetupAndroidRoute,
  AuthenticatedSetupGmailRoute: AuthenticatedSetupGmailRoute,
  AuthenticatedSetupNotificationsRoute: AuthenticatedSetupNotificationsRoute,
  AuthenticatedSetupSyncRoute: AuthenticatedSetupSyncRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
