/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedSetupGmailRouteImport } from './routes/_authenticated/setup.gmail'
import { Route as AuthenticatedPlannerPreferencesRouteImport } from './routes/_authenticated/planner.preferences'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupGmailRoute = AuthenticatedSetupGmailRouteImport.update({
  id: '/setup/gmail',
  path: '/setup/gmail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerPreferencesRoute =
  AuthenticatedPlannerPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/app': typeof AuthenticatedAppRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/planner/preferences': typeof AuthenticatedPlannerPreferencesRoute
  '/setup/gmail': typeof AuthenticatedSetupGmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/app': typeof AuthenticatedAppRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/planner/preferences': typeof AuthenticatedPlannerPreferencesRoute
  '/setup/gmail': typeof AuthenticatedSetupGmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/index': typeof Char91indexChar93Route
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/planner/preferences': typeof AuthenticatedPlannerPreferencesRoute
  '/_authenticated/setup/gmail': typeof AuthenticatedSetupGmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/index'
    | '/app'
    | '/planner'
    | '/tasks'
    | '/planner/preferences'
    | '/setup/gmail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/index'
    | '/app'
    | '/planner'
    | '/tasks'
    | '/planner/preferences'
    | '/setup/gmail'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/index'
    | '/_authenticated/app'
    | '/_authenticated/planner'
    | '/_authenticated/tasks'
    | '/_authenticated/planner/preferences'
    | '/_authenticated/setup/gmail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup/gmail': {
      id: '/_authenticated/setup/gmail'
      path: '/setup/gmail'
      fullPath: '/setup/gmail'
      preLoaderRoute: typeof AuthenticatedSetupGmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner/preferences': {
      id: '/_authenticated/planner/preferences'
      path: '/preferences'
      fullPath: '/planner/preferences'
      preLoaderRoute: typeof AuthenticatedPlannerPreferencesRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
  }
}

interface AuthenticatedPlannerRouteChildren {
  AuthenticatedPlannerPreferencesRoute: typeof AuthenticatedPlannerPreferencesRoute
}

const AuthenticatedPlannerRouteChildren: AuthenticatedPlannerRouteChildren = {
  AuthenticatedPlannerPreferencesRoute: AuthenticatedPlannerPreferencesRoute,
}

const AuthenticatedPlannerRouteWithChildren =
  AuthenticatedPlannerRoute._addFileChildren(AuthenticatedPlannerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedSetupGmailRoute: typeof AuthenticatedSetupGmailRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedSetupGmailRoute: AuthenticatedSetupGmailRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  Char91indexChar93Route: Char91indexChar93Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
